# TIỀN XỬ LÝ DỮ LIỆU #

## GIỚI THIỆU BỘ DỮ LIỆU BAN ĐẦU  ##

### Nạp dữ liệu ###

In [14]:
import pandas as pd
train = pd.read_csv("C:/Users/USER/Downloads/d-doan-l-ng-tieu-th-di-n-nang-usage-k-wh/train.csv",encoding="latin1")
test = pd.read_csv("C:/Users/USER/Downloads/d-doan-l-ng-tieu-th-di-n-nang-usage-k-wh/test.csv",encoding="latin1")

### Đọc dữ liệu ###

In [15]:
display(train)

,date,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus_Weekday,WeekStatus_Weekend,Day_of_week_Friday,Day_of_week_Monday,Day_of_week_Saturday,Day_of_week_Sunday,Day_of_week_Thursday,Day_of_week_Tuesday,Day_of_week_Wednesday,Load_Type_Light_Load,Load_Type_Maximum_Load,Load_Type_Medium_Load
0,4/7/2018 17:15,4.18,0.00,21.78,0.00,100.00,18.85,62100,False,True,False,False,True,False,False,False,False,False,False,True
1,5/30/2018 2:45,2.92,4.93,0.00,0.00,50.96,100.00,9900,True,False,False,False,False,False,False,False,True,True,False,False
2,2/23/2018 1:45,6.44,7.34,0.00,0.00,65.95,100.00,6300,True,False,True,False,False,False,False,False,False,True,False,False
3,12/13/2018 13:30,56.92,22.28,0.00,0.03,93.12,100.00,48600,True,False,False,False,False,False,True,False,False,False,False,True
4,4/15/2018 2:45,3.10,3.82,0.00,0.00,63.01,100.00,9900,False,True,False,False,False,True,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28027,6/25/2018 12:45,5.76,0.00,25.27,0.00,100.00,22.22,45900,True,False,False,True,False,False,False,False,False,False,False,True
28028,3/7/2018 6:30,3.71,4.57,0.00,0.00,63.03,100.00,23400,True,False,False,False,False,False,False,False,True,True,False,False
28029,4/28/2018 13:15,13.57,0.14,14.33,0.01,99.99,68.76,47700,False,True,False,False,True,False,False,False,False,False,True,False
28030,1/9/2018 23:15,4.64,4.32,0.00,0.00,73.19,100.00,83700,True,False,False,False,False,False,False,True,False,True,False,False
28031,6/14/2018 13:00,6.70,0.00,20.05,0.00,100.00,31.69,46800,True,False,False,False,False,False,True,False,False,False,False,True

In [16]:
display(test)

,date,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus_Weekday,WeekStatus_Weekend,Day_of_week_Friday,Day_of_week_Monday,Day_of_week_Saturday,Day_of_week_Sunday,Day_of_week_Thursday,Day_of_week_Tuesday,Day_of_week_Wednesday,Load_Type_Light_Load,Load_Type_Maximum_Load,Load_Type_Medium_Load
0,2018-04-29 07:15:00,3.82,0.00,0.00,60.20,100.00,26100,False,True,False,False,False,True,False,False,False,True,False,False
1,2018-10-04 12:00:00,48.02,0.00,0.03,78.46,100.00,43200,True,False,False,False,False,False,True,False,False,False,True,False
2,2018-01-26 11:30:00,59.65,0.00,0.06,89.61,100.00,41400,True,False,True,False,False,False,False,False,False,False,True,False
3,2018-06-02 14:30:00,0.00,16.60,0.00,100.00,18.53,52200,False,True,False,False,True,False,False,False,False,True,False,False
4,2018-12-07 15:00:00,20.99,0.00,0.03,94.19,100.00,54000,True,False,True,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7003,2018-04-05 05:15:00,3.85,0.00,0.00,63.56,100.00,18900,True,False,False,False,False,False,True,False,False,True,False,False
7004,2018-06-09 03:15:00,5.54,0.00,0.00,46.63,100.00,11700,False,True,False,False,True,False,False,False,False,True,False,False
7005,2018-02-01 12:00:00,81.94,0.00,0.07,87.13,100.00,43200,True,False,False,False,False,False,True,False,False,False,True,False
7006,2018-12-01 08:15:00,2.59,0.14,0.00,82.00,99.93,29700,False,True,False,False,True,False,False,False,False,True,False,False
7007,2018-04-14 10:30:00,0.86,1.19,0.02,99.97,99.95,37800,False,True,False,False,True,False,False,False,False,False,True,False

### In ra 5 dòng đầu ###

In [ ]:
import numpy as np
from scipy import stats
def duplicates(train):
    duplicate_rows_train = train[train.duplicated()]
    if duplicate_rows_train.shape[0] > 0:
        print('Số dòng trước khi loại bỏ:', df.count()[0])
        print('Số dòng trùng:', duplicate_rows_train.shape[0])
        train = train.drop_duplicates()
        print('Số dòng sau khi loại bỏ:', train.count()[0])
    else:
        print('Không có dòng trùng.')
    return train

def drop_na(train, threshold_NaN):
    isna_stat = (train.isna().sum() / train.shape[0]).sort_values(ascending=True)
    drop_cols = []
    if isna_stat.max() > 0.0:
        drop_cols = np.array(isna_stat[isna_stat > threshold_NaN].index)
        print('Loại bỏ cột chứa hơn', threshold_NaN * 100, '% NaN:', drop_cols)
        train = train.drop(drop_cols, axis=1)
    else:
        print('Không cần loại bỏ cột.')
    return train, drop_cols

def imputation(train):
    isna_stat = (train.isna().sum() / train.shape[0]).sort_values(ascending=True)
    if isna_stat.max() > 0.0:
        print('Điền NaN bằng IterativeImputer')
        train = pd.DataFrame(IterativeImputer(random_state=0).fit_transform(train), columns=train.columns)
    else:
        print('Không cần điền dữ liệu.')
    return train

data = train.copy()
# Lấy cột số
numeric_columns = data.select_dtypes(include='number').columns

# Tính Q1, Q3, IQR
Q1 = data[numeric_columns].quantile(0.25)
Q3 = data[numeric_columns].quantile(0.75)
IQR = Q3 - Q1

# Lọc từng cột (theo cách giống for trong R)
for col in numeric_columns:
    lower_bound = Q1[col] - 1.5 * IQR[col]
    upper_bound = Q3[col] + 1.5 * IQR[col]
    data = data[(data[col] >= lower_bound) & (data[col] <= upper_bound)]

# In số dòng bị loại và còn lại
print(f"Số dòng ban đầu: {train.shape[0]}")
print(f"Số dòng còn lại sau khi loại outliers: {data.shape[0]}")
print(f"Số dòng bị loại bỏ: {train.shape[0] - data.shape[0]}")

# Thực hiện tiền xử lý
threshold_NaN = 0.5
threshold_Z = 3.0 
train = duplicates(train)
train, drop_cols = drop_na(train, threshold_NaN)
train = imputation(train)

Số dòng ban đầu: 28032
Số dòng còn lại sau khi loại outliers: 20384
Số dòng bị loại bỏ: 7648
Không có dòng trùng.
Không cần loại bỏ cột.
Không cần điền dữ liệu.